apiVersion: skaffold/v1
kind: Config
metadata:
  name: poc-spring-cloud-kubernetes
build:
  local:
    push: false
  artifacts:
  - image: poc-spring-cloud-kubernetes
    jib:
      type: maven
      project: com.github.bilak-poc:poc-spring-cloud-kubernetes
deploy:
  kubectl:
    manifests: ["k8s/*.yaml"]
