apiVersion: v1
kind: Service
metadata:
  name: poc-spring-cloud-kubernetes
spec:
  type: LoadBalancer
  selector:
    app: poc-spring-cloud-kubernetes
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: debug
      port: 5005
      targetPort: 5005